services:
  - type: web
    name: bamania-software-hub
    env: node
    plan: free
    buildCommand: npm install && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
